# config.yaml

network_interfaces:
  mac:
    - "en0"
    - "en1"
    - "en2"
  linux:
    - "eth0"
    - "eth1"
    - "enp0s3"
    - "enp1s0"
    - "eno1"
    - "eno2"
    - "wlan0"
    - "wlan1"

telegram:
  token: "your_bot_token"
  chat_id: "your_chat_id"
